### ISSUE TITLE
可否配置多节点

### ISSUE THREAD

**Issue by xtqjh** [1981430140/egg-elasticsearch-ts#1]
exports.elasticsearch = {
    node: 'http://172.16.110.33:9200',
    node: 'http://172.16.110.34:9200',
  };

**Comment by 1981430140** [comment]
可以的，参考 [@elastic/elasticsearch](https://www.npmjs.com/package/@elastic/elasticsearch)

**Comment by 1981430140** [comment]
参考 https://github.com/elastic/elasticsearch-js/blob/master/index.d.ts 中的 ClientOptions
![image](https://user-images.githubusercontent.com/48678160/125584979-824b4346-be29-4739-90da-bf4d6e7921d1.png)

@xtqjh

**Comment by xtqjh** [comment]
exports.elasticsearch = {
  node: [
    { url: new URL('http://172.16.111.24:9200'), id: 'esa' },
    { url: new URL('http://172.16.110.33:9200'), id: 'esb' },
  ],
};


配置了多数据源后如何使用指定数据源呢？

this.app.elasticsearch.search()

**Comment by xtqjh** [comment]
是这样的！！
随着项目的迭代，项目上使用了es又有多个版本[1.7，6.8，7.6]的数据源
现在新开了一个项目，需要将多个版本的数据源整合

**Comment by 1981430140** [comment]
最新版支持多数据源

**Comment by xtqjh** [comment]
Object.assign(this.app, { elasticsearchs, elasticsearch: elasticsearchSingle });

这就意味着app下有 elasticsearchs 与 elasticsearch 两个es相关的属性

**Comment by 1981430140** [comment]
是的

**Comment by 1981430140** [comment]
你这有什么好的提议可以说说的
